# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Corne-ish Zen Left)
        run: >-
          west build
          -s zmk/app
          -b corne-ish_zen_left
          --
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Corne-ish Zen DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/corne-ish_zen_left.dts.pre.tmp
      - name: Corne-ish Zen Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corneish_zen_left.uf2
      - name: Archive (Corne-ish Zen Left)
        uses: actions/upload-artifact@v2
        with:
          name: corneish_zen_firmware-${{ steps.date.outputs.date }}
          path: corneish_zen_left.uf2
      - name: West Build (Corne-ish Zen Right)
        run: >-
          west build
          --pristine
          -s zmk/app
          -b corne-ish_zen_right
          --
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Corne-ish Zen Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 corneish_zen_right.uf2
      - name: Archive (Corne-ish Zen Right)
        uses: actions/upload-artifact@v2
        with:
          name: corneish_zen_firmware-${{ steps.date.outputs.date }}
          path: corneish_zen_right.uf2
